# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-07 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 7, 21, 16, 1, 762389, tzinfo=utc))),
                ('endTime', models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 7, 21, 16, 1, 762414, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('availStart', models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 7, 21, 16, 1, 761722, tzinfo=utc))),
                ('availEnd', models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 7, 21, 16, 1, 761756, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resres.Users'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resres.Resource'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resres.Users'),
        ),
    ]
