# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 22:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
