# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 18, 46, 326946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 18, 46, 326921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 18, 46, 326344, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 18, 46, 326292, tzinfo=utc)),
        ),
    ]
