# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0002_auto_20170511_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
