# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0002_auto_20170508_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.TimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 27, 32, 885730, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.TimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 27, 32, 885708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='end',
            field=models.TimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 27, 32, 885276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='start',
            field=models.TimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 27, 32, 885243, tzinfo=utc)),
        ),
    ]
