# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0003_auto_20170508_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 27, 57, 690208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 27, 57, 690183, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 27, 57, 689710, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 27, 57, 689675, tzinfo=utc)),
        ),
    ]
