# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0003_auto_20170511_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
