# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0004_auto_20170508_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 35, 52, 115609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 35, 52, 115587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 35, 52, 115060, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 5, 8, 20, 35, 52, 115010, tzinfo=utc)),
        ),
    ]
