# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0005_auto_20170508_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='end',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='start',
            field=models.BigIntegerField(),
        ),
    ]
