# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0005_reservation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='lastreservation',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
