# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0006_resource_lastreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2017, 5, 12)),
        ),
    ]
