# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0006_auto_20170508_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
