# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-09 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0007_resource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
