# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0007_auto_20170512_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 18, 55, 49, 250615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resource',
            name='lastreservation',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 18, 55, 49, 250090, tzinfo=utc)),
        ),
    ]
