# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0008_auto_20170512_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resource',
            name='lastreservation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
