# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resres', '0009_auto_20170512_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='currentcount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservationcount',
            field=models.BigIntegerField(default=0),
        ),
    ]
